// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt_MVC.Data;

#nullable disable

namespace Projekt_MVC.Migrations
{
    [DbContext(typeof(ForumDB))]
    [Migration("20240109163805_jj")]
    partial class jj
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projekt_MVC.Models.Dyskusja", b =>
                {
                    b.Property<int>("DyskusjaId")
                        .HasColumnType("int");

                    b.Property<bool?>("CzyPrzyklejony")
                        .HasColumnType("bit");

                    b.Property<int?>("IdForum")
                        .HasColumnType("int");

                    b.Property<int>("IdUzytkownika")
                        .HasColumnType("int");

                    b.Property<int?>("LiczbaOdpowiedzi")
                        .HasColumnType("int");

                    b.Property<int?>("LiczbaOdwiedzen")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Temat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DyskusjaId");

                    b.HasIndex("IdForum");

                    b.ToTable("Dyskusja");
                });

            modelBuilder.Entity("Projekt_MVC.Models.Forum", b =>
                {
                    b.Property<int>("IdForum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdForum"));

                    b.Property<int>("IdKategorii")
                        .HasColumnType("int");

                    b.Property<int>("IdUprawnien")
                        .HasColumnType("int");

                    b.Property<int?>("LiczbaWatkow")
                        .HasColumnType("int");

                    b.Property<int?>("LiczbaWiadomosci")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdForum");

                    b.HasIndex("IdKategorii");

                    b.HasIndex("IdUprawnien");

                    b.ToTable("Forum");
                });

            modelBuilder.Entity("Projekt_MVC.Models.Kategoria", b =>
                {
                    b.Property<int>("IdKategorii")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKategorii"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKategorii");

                    b.ToTable("Kategoria");
                });

            modelBuilder.Entity("Projekt_MVC.Models.Moderator", b =>
                {
                    b.Property<int>("IdModeratora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModeratora"));

                    b.Property<int>("ForumIdForum")
                        .HasColumnType("int");

                    b.Property<int>("IdForum")
                        .HasColumnType("int");

                    b.Property<int>("IdUzytkownika")
                        .HasColumnType("int");

                    b.HasKey("IdModeratora");

                    b.HasIndex("ForumIdForum");

                    b.HasIndex("IdUzytkownika");

                    b.ToTable("Moderator");
                });

            modelBuilder.Entity("Projekt_MVC.Models.Odpowiedz", b =>
                {
                    b.Property<int>("OdpowiedzId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataOdpowiedzi")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDyskusji")
                        .HasColumnType("int");

                    b.Property<int>("IdUzytkownika")
                        .HasColumnType("int");

                    b.Property<string>("Tresc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZalacznikPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OdpowiedzId");

                    b.HasIndex("IdDyskusji");

                    b.ToTable("Odpowiedz");
                });

            modelBuilder.Entity("Projekt_MVC.Models.Ogloszenie", b =>
                {
                    b.Property<int>("IdOgloszenia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOgloszenia"));

                    b.Property<int>("IdUzytkownika")
                        .HasColumnType("int");

                    b.Property<string>("Tresc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdOgloszenia");

                    b.HasIndex("IdUzytkownika");

                    b.ToTable("Ogloszenie");
                });

            modelBuilder.Entity("Projekt_MVC.Models.Ranga", b =>
                {
                    b.Property<int>("IdRangi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRangi"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PotrzebnaLiczbaWiadomosci")
                        .HasColumnType("int");

                    b.HasKey("IdRangi");

                    b.ToTable("Ranga");
                });

            modelBuilder.Entity("Projekt_MVC.Models.RangaUzytkownika", b =>
                {
                    b.Property<int>("IdRangiUzytkownika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRangiUzytkownika"));

                    b.Property<int>("IdRangi")
                        .HasColumnType("int");

                    b.Property<int>("IdUzytkownika")
                        .HasColumnType("int");

                    b.HasKey("IdRangiUzytkownika");

                    b.HasIndex("IdRangi");

                    b.HasIndex("IdUzytkownika");

                    b.ToTable("RangaUzytkownika");
                });

            modelBuilder.Entity("Projekt_MVC.Models.Role", b =>
                {
                    b.Property<int>("IdRoli")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRoli"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRoli");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Projekt_MVC.Models.UprawnienieAnonimowych", b =>
                {
                    b.Property<int>("IdUprawnienia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUprawnienia"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUprawnienia");

                    b.ToTable("UprawnienieAnonimowych");
                });

            modelBuilder.Entity("Projekt_MVC.Models.User", b =>
                {
                    b.Property<int>("IdUzytkownika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUzytkownika"));

                    b.Property<string>("AvatarPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Haslo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("IdRoli")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("IdUzytkownika");

                    b.HasIndex("IdRoli");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Projekt_MVC.Models.Dyskusja", b =>
                {
                    b.HasOne("Projekt_MVC.Models.User", "Wlasciciel")
                        .WithMany("Dyskusje")
                        .HasForeignKey("DyskusjaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Projekt_MVC.Models.Forum", "Forum")
                        .WithMany()
                        .HasForeignKey("IdForum");

                    b.Navigation("Forum");

                    b.Navigation("Wlasciciel");
                });

            modelBuilder.Entity("Projekt_MVC.Models.Forum", b =>
                {
                    b.HasOne("Projekt_MVC.Models.Kategoria", "Kategoria")
                        .WithMany()
                        .HasForeignKey("IdKategorii")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projekt_MVC.Models.UprawnienieAnonimowych", "UprawnienieAnonimowych")
                        .WithMany("Forum")
                        .HasForeignKey("IdUprawnien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategoria");

                    b.Navigation("UprawnienieAnonimowych");
                });

            modelBuilder.Entity("Projekt_MVC.Models.Moderator", b =>
                {
                    b.HasOne("Projekt_MVC.Models.Forum", "Forum")
                        .WithMany("Moderatorzy")
                        .HasForeignKey("ForumIdForum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projekt_MVC.Models.User", "Uzytkownik")
                        .WithMany("Moderatorzy")
                        .HasForeignKey("IdUzytkownika")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Forum");

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("Projekt_MVC.Models.Odpowiedz", b =>
                {
                    b.HasOne("Projekt_MVC.Models.Dyskusja", "Dyskusja")
                        .WithMany("Odpowiedzi")
                        .HasForeignKey("IdDyskusji")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projekt_MVC.Models.User", "Autor")
                        .WithMany("Odpowiedzi")
                        .HasForeignKey("OdpowiedzId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Dyskusja");
                });

            modelBuilder.Entity("Projekt_MVC.Models.Ogloszenie", b =>
                {
                    b.HasOne("Projekt_MVC.Models.User", "Uzytkownik")
                        .WithMany("Ogloszenia")
                        .HasForeignKey("IdUzytkownika")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("Projekt_MVC.Models.RangaUzytkownika", b =>
                {
                    b.HasOne("Projekt_MVC.Models.Ranga", "Ranga")
                        .WithMany()
                        .HasForeignKey("IdRangi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projekt_MVC.Models.User", "Uzytkownik")
                        .WithMany()
                        .HasForeignKey("IdUzytkownika")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ranga");

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("Projekt_MVC.Models.User", b =>
                {
                    b.HasOne("Projekt_MVC.Models.Role", "Rola")
                        .WithMany("Uzytkownicy")
                        .HasForeignKey("IdRoli")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rola");
                });

            modelBuilder.Entity("Projekt_MVC.Models.Dyskusja", b =>
                {
                    b.Navigation("Odpowiedzi");
                });

            modelBuilder.Entity("Projekt_MVC.Models.Forum", b =>
                {
                    b.Navigation("Moderatorzy");
                });

            modelBuilder.Entity("Projekt_MVC.Models.Role", b =>
                {
                    b.Navigation("Uzytkownicy");
                });

            modelBuilder.Entity("Projekt_MVC.Models.UprawnienieAnonimowych", b =>
                {
                    b.Navigation("Forum");
                });

            modelBuilder.Entity("Projekt_MVC.Models.User", b =>
                {
                    b.Navigation("Dyskusje");

                    b.Navigation("Moderatorzy");

                    b.Navigation("Odpowiedzi");

                    b.Navigation("Ogloszenia");
                });
#pragma warning restore 612, 618
        }
    }
}
